language: python

sudo: false

env:
  - TOXENV=py34-flake8
  - TOXENV=py34-isort
  - TOXENV=py27
  - TOXENV=py34

matrix:
  include:
    - python: 3.3
      env:
      - TOXENV=py33
    - python: 3.5
      env:
      - TOXENV=py35
    - python: 3.6
      env:
      - TOXENV=py36

install:
  - pip install tox flake8 pep8-naming isort codecov

script:
  - tox

after_success:
  - codecov -e TOXENV
