# This workflow will install Python dependencies, run flake8, isort and integration tests with tox

name: Python tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        run: sudo add-apt-repository -y ppa:deadsnakes/ppa && sudo apt-get install -y python3.6 python3.7 python3.9 python3.6-distutils python3.7-distutils python3.9-distutils

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install responses requests six isort flake8 nose tox
      
      - name: Create config for integration tests
        run: 'echo altapay_account=\"${{secrets.GATEWAYUSER}}\" > __init__.py && echo altapay_password=\"${{secrets.GATEWAYPASS}}\" >> __init__.py && echo altapay_url=\"${{secrets.GATEWAYURL}}/merchant/\" >> __init__.py && echo altapay_test_terminal_name=\"${{secrets.CC_TERMINAL_NAME}}\" >> __init__.py && echo altapay_invoice_test_terminal_name=\"${{ secrets.INVOICE_TERMINAL_NAME}}\" >> __init__.py && echo altapay_contract_identifier=\"${{ secrets.GATEWAY_CONTRACT_IDENTIFIER }}\" >> __init__.py'
        working-directory: tests/integration  
      
      - name: Run tests with tox
        run: tox
